application: git-hop
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
  application_readable: true
- url: /digest/cron
  script: _go_app
  login: admin
- url: /admin/.*
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
  secure: always
